### ISSUE TITLE
Undefined method error

### ISSUE THREAD

**Issue by alexiamcdonald** [olejrosendahl/simplemde-rails#1]
Heya!

I really want to use your gem but I'm getting a

```undefined method `simplemde_text_area' for #<SimpleForm::FormBuilder:0x007ff56d571998>```

is this gem still up to date?

**Comment by alexiamcdonald** [comment]
Sorry, I just realized yours was unpublished and it was another person's gem I was using sorry for wasting your time. 😄

**Comment by olejrosendahl** [comment]
Hi @alexiamcdonald,

Sorry, this project was abandoned before it was completed. We manage to make it work quite easily with the existing SimpleMDE features.

Import the assets from the CDN or copy them into `vendor/assets`. The attach the editor as described [here](https://github.com/NextStepWebs/simplemde-markdown-editor#using-a-specific-textarea).

**Comment by alexiamcdonald** [comment]
@olejrosendahl This is totally an awesome idea though! You should totally get it published when you decide to finish it 😃

**Comment by olejrosendahl** [comment]
Thanks for the motivation @alexiamcdonald 😃, I'll find some time for it soon.

**Comment by petrosp** [comment]
> Sorry, this project was abandoned before it was completed.

Sad to hear, but please have that noted in the `README` and save us some precious time
